CREATE TABLE CATEGORIA (
    id INTEGER PRIMARY KEY,
    nome VARCHAR(200) NOT NULL
);

CREATE TABLE ORGAO (
    id INTEGER PRIMARY KEY,
    nome VARCHAR(200) NOT NULL
);

CREATE TABLE MODALIDADE (
    id INTEGER PRIMARY KEY,
    nome VARCHAR(200) NOT NULL
);

CREATE TABLE FONTE (
    id INTEGER PRIMARY KEY,
    nome VARCHAR(200) NOT NULL
);

CREATE TABLE MOVIMENTACAO (
    id INTEGER PRIMARY KEY auto_increment,
    ano INTEGER NOT NULL,
    mes VARCHAR(10) NOT NULL,
    categoria_id INTEGER NOT NULL,
    orgao_id INTEGER NOT NULL,
    modalidade_id INTEGER NOT NULL,
    fonte_id INTEGER NOT NULL,
    valor NUMERIC NOT NULL
);

 ALTER TABLE MOVIMENTACAO
    ADD FOREIGN KEY (categoria_id)
    REFERENCES CATEGORIA(id);

 ALTER TABLE MOVIMENTACAO
    ADD FOREIGN KEY (modalidade_id)
    REFERENCES MODALIDADE(id);

 ALTER TABLE MOVIMENTACAO
    ADD FOREIGN KEY (fonte_id)
    REFERENCES FONTE(id);